export const getPodcast = 'getPodcast';
export const loadingPodcast = 'loadingPodcast';
export const errorPodcast = 'errorPodcast';
export const getAllPodcast = 'getAllPodcast';
export const categoryPodcast = 'categoryPodcast';
export const likeOrDislikePodcast = 'likeOrDislikePodcast';
export const commentPodcast = 'commentPodcast';
export const deleteComment = 'deleteComment';
export const idSearchPodcast= 'idSearchPodcast';